# .github/workflows/broken-pipeline.yml (CONTIENE ERRORES)
name: Broken CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]  
  pull_request:
    branches: [ main ]

jobs:
  test:
    defaults:
      run:
        working-directory: "D1-05-CI-CD-Publishing/desafio 4/"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9 
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tests
        run: python -m pytest tests/ --verbose
        
  build:
    defaults:
      run:
        working-directory: "D1-05-CI-CD-Publishing/desafio 4/"
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker image
        run: |
          docker build -t myapp:${{ GITHUB.SHA }} .  
          docker tag myapp:${{ GITHUB.SHA }} myapp:latest
      
      - name: Save Docker image
        run: |
          docker save myapp:latest | tee myapp.tar
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: "D1-05-CI-CD-Publishing/desafio 4/myapp.tar"

  deploy:
    needs: [test, build]
    runs-on: ubuntu-latest
    environment: production
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
      
      - name: Load Docker image
        run: docker load < myapp.tar
      
      - name: Deploy application
        run: |
          echo "Deploying to production..."
          docker run -d -p 8080:8080 --name myapp-prod myapp:latest
          
      - name: Health check
        run: |
          sleep 10
          curl -f http://localhost:8080/health || exit 1  