name: definir mi archivo env

on:
  push:
    branches:
      - main 

jobs:
  test_envs:
    runs-on: ubuntu-latest
    env:
      PROYECTO_NOMBRE: "MiProyectoApp"
    steps:
      - name: definir variable a nivel de step
        env: 
          VERSION_APP: "1.0.0"
        run: echo 'Es obligatorio agregar una propiedad "uses" o "run"'
      - name: Mostrar el valor de la variable declarada a nivel de jobs
        run: |
          echo "El valor de la variable PROYECTO_NOMBRE es: ${PROYECTO_NOMBRE}"
      - name: Mostrar el valor de la variable declarada a nivel de step
        run: |
          echo "El valor de la variable VERSION_APP es: ${VERSION_APP}"
      - name: Mostrar una variable por defecto de GitHub
        run: |
          echo "Se muestra el valor de la variable GITHUB_ENV: ${{ github.env }}"
          echo "También la variable GITHUB_RUN_ID: ${{ github.run_id }}" 
          echo "Y el nombre del contenedor creado para este job: ${{ runner.name }}"
