name: secretos en actions

on:
  push:
    branches:
      - main

jobs:
  usar_secreto:
    runs-on: ubuntu-latest
    steps:
      - name: secreto 
        run: |
          echo "el valor del secreto es: ${{ secrets.MY_SUPER_SECRET }}"
