name: cron

on:
  workflow_dispatch:
  # https://docs.github.com/es/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule
  schedule:
    - cron: '0 3 * * *'
jobs:
  tarea_programada_o_manual:
    runs-on: ubuntu-latest
    steps:
      - name: log
        run: echo "Ejecutado desde ${{github.event_name}}"
