# D1-02-Secrets-Env-Vars/.github/workflows/debugging_secret_access_fail.yml
name: Debugging Secret/Env Access

on: [push]

env:
  # Variable de entorno de job definida incorrectamente (sintaxis)
  JOB_ENV_VAR: incorrect-env-access

jobs:
  access-data:
    runs-on: ubuntu-latest
    steps:
      - name: Try to access job env
        run: |
          echo "Job Env: ${{ env.JOB_ENV_VAR }}" # Error: Sintaxis de acceso a variable de entorno en 'run'
      - name: Try to access step env (will fail if above is fixed)
        env:
          STEP_ENV_VAR: "StepValue"
        run: |
          echo "Step Env: $STEP_ENV_VAR"
      - name: Try to access a secret
        run: |
          echo "Secret: ${{ secrets.NON_EXISTENT_SECRET }}" # Error: Secreto inexistente