name: Depuración de Trigger Fallido

on:
  push:
    branches-ignore:
      - 'main' # Esto es un error intencional, no funcionará como se espera para "no main"
      # https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#push

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Show branch
        run: |
          echo "Esta rama es: ${{ github.ref }}"