name: Releases

on:
  push:
    tags:
      - 'v*'

jobs:
  compile:
    runs-on: ubuntu-latest 
    name: Compilación del paquete
    defaults:
      run:
        working-directory: D1-05-CI-CD-Publishing/desafio 3
    steps:
      - name: Checkout del proyecto
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Instalación entorno node
        uses: actions/setup-node@v4
      - name:  configurar repositorio
        run: |
          echo "@$(echo $GITHUB_REPOSITORY | cut -d/ -f1):registry=https://npm.pkg.github.com/" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGE }}" >> .npmrc
      - name: Compilación
        run: |
          bash build.sh
      - name: publicacion
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGE }}