name: Coding Artifacts

on:
  push:
    branches:
      - main

jobs:
  crear-cache:
    name: GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - name: Importar repositorio
        uses: actions/checkout@v4
        with:
          repository: LuisDelgado-LD/proyecto-integrador-dh-frontend

      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          key: ${{ hashFiles('**/package-lock.json') }}
          path: node_modules/
          restore-keys: ${{ hashFiles('**/package-lock.json') }}
      - name: Construccion de paquete Node.js
        run: npm install >> instalacion.txt
      - name: Subir artefactos
        uses: actions/upload-artifact@v4
        with:
          name: "Resultado instalacion"
          path: "instalacion.txt"
          overwrite: true

          #Para remover un artifact se puede hacer desde la interfaz en Actions > CodeQL > Artifacts > Delete
          #Tambien si se elimina una ejecucion se eliminan los artifacts de esa ejecucion