name: Coding Repo Secret

on:
  push:
    branches:
      - main

jobs:
  usar_secreto:
    runs-on: ubuntu-latest
    steps:
      - name: mostrar usar_secreto (enmascarado)
        run: |
          echo "::add-mask::${{ secrets.MY_SUPER_SECRET }}"
          echo "El secreto es: ${{ secrets.MY_SUPER_SECRET }}"
