name: Custom Envs

on:
  push:
    branches:
      - main

jobs:
  test_envs:
    runs-on: ubuntu-latest

    env:
      PROYECTO_NOMBRE: Nombre Del PROYECTO

    steps:
      - name: Show variable
        run: echo "El nombre del proyecto es: $PROYECTO_NOMBRE"
      - name: Show version
        env:
          VERSION_APP: 1.0.0
        run: echo "La version de la app es: $VERSION_APP"
      - name: Github variable
        run: echo "El nombre del repositorio es: $GITHUB_REPOSITORY"
      