name: Coding Repo Secret

on:
  push:
    branches:
      - main

jobs:
  usar_secreto:
    runs-on: ubuntu-latest
    steps:
      - name: mostrar usar_secreto (enmascarado)
        run: |
          echo "::add-mask::${{ secrets.MY_SUPER_SECRET }}"
          export MY_SUPER_SECRET_LAST3=$(echo "${{ secrets.MY_SUPER_SECRET }}" | rev | cut -c1-3 | rev)
          echo "El secreto termina en: ${MY_SUPER_SECRET_LAST3}"
